Attribute VB_Name = "HighLitePivotTable"
Option Explicit
Const cThisMeet = "2019-03-31 Champs"
Const cDisableScreenUpdating = vbTrue
Const cDP = vbFalse 'flag for enabling debug.print statements - Global
Const cEventFilePath = "\Events.csv"
'Public sEvent As String
Const gbAppend = vbFalse
Dim iEventFile As Integer
Const cRTS = "+=" 'cRankTimeSeparator
Const cCKS = ":" 'CollKeySeparator


Public Sub SetTimeFormat()
'not working
       Selection.NumberFormat = "00"":""00"".""00"
End Sub

Sub ReadMe()
'The Main Routine is Main
'Special formating for the Time column
    'Columns("E:E").Select
    'Selection.NumberFormat = "00"":""00"".""00"
Debug.Print cEventFilePath
End Sub
Sub Main()
Const cThisSub = "Main: "
Debug.Print cThisSub & "Begins at " & Date & " " & Time()
    Call HiLite
Debug.Print cThisSub & "Ends at " & Date & " " & Time()
End Sub
Sub HiLite()
'Main Routine
'Triggered by MakePT button.
'What happens:
    'Existing pivot tables are removed and then rebuilt.
    'Hilite/emphasis is added to the Pivot Tables.
        '(On the PIVOT Tables Highlight the Best Time if it is from the last meet.)
        'Make a short version of the Pivot Table
        'Make a list of New Best Times
'FAJ 12/10/2016
'Rev 1.0
'Rev 2.0 12/11/2016
    'Reset Highlights before setting.
    'Use constants to search for Meet.
'Rev 3.0
    'Added debugging statements and optimizations on array clearing.
'Rev 4.0
    'New Highlight scheme
    'Creation of PivotTables
    'Invoke subroutine to create PivotTables
'Rev 5.0 2/26/2017
    'Place page breaks in Pivot Table. THIS ISNT GOOD. *****Still have to do it by hand because OTHER
    'page breaks may split a swimmer.
    'Removed 999999 records from data.
    'Macro to Shorten Pivot Table, copy it, restore it.
    'Rev 6.0 3/8/2017
    'Create short Pivot Table.
    'Stop screen updating
'Rev 7.0
    'Sublist of New Personal Best
    'Corrected New Personal Best criteria - Fastest time must be from this Meet and entries for other Meets have to exist.
    'Highlight Time and Name
    'Perhaps a MR and FR with Swimmer should not be higlited.
'Rev 7.1 2017-11-24
    'Added Sub PasteSwimEvents
    'Requires user to manually put events generated by MeetResults.xlsm on the clipboard
    'and position cursor on this spreadsheet.
    'Added message showing number of NewBestTimes.
    'More use of FindColumnInTopRowInTopRow
    'Range arguments for PivotCaches.Create and CreatePivotTable - Not recommended! (See sub CreatePivotTable) label MayNotWork
'Rev 7.11 D 2017-12-25
    'PasteSwimEvents reads the events file and pastes (appends) swim event data.
    'New column - if new best time - the time difference between the previous best times and current best time.
'Rev 7.20 E 2018-02-17
    'Erased delta times from previous runs.
    'Added criteria for New Best Time. It is not a best time if it matches the previous meet also. Thank you Jacob Kurtz.
    'Referenced Pivot Table properties to locate the last row.
    'Got rid of GrandTotals in pivot table
    'Fixed DeltaTime - calculation of minutes was wrong.
'Rev 8.0 F 2018-02-17
    'Replaced fixed array size with a dynamic array.
    'FindNextName - added another return argument 'iThisNameRow
    'Deleted unnecessary hilite removing code since all formatting is removed when the pivot table is created.
'Rev 8.1 F 2018-02-17
    'Renamed Function DeltaTime to SwimTime which does addition and subtraction.
'Rev 8.2 F 2018-03-16
    'Replaced PasteSwimEvents (old one is PasteSwimEventsDeprecated) Makes reference to ThisWorkSheet.Path
'Rev 8.3 2018-12-04
    'Using collection to cash Meet name associated with Best Time for display alongside of the short pivot table.
    'Major enhancements to supporting subroutines "CreatePivotTable" and "CopyAndShortenPivotTable".
    'Additional subroutine "AppendMeetToPV"
'Rev 8.4 2019-03-31
    'In section GetDeltaTime: When comparing Event Times covert string to Lng using cLng.
    'In section BuildTwoCollections: Was building duplicate keys for collections when swimmer got a time in this meet (latest run), that is the fastest AND that time was identical to a previous meet.

'Const cDP = vbFalse 'flag for enabling debug.print statements.

'Const cThisMeet = "2019-01-06 Plainview"
'Const cThisMeet = "2018-12-16 Long Beach"
'Const cThisMeet = "2018-02-04 N. Hempstead"
Const cThisSub = "HiLite: "
Const cPVNAME = "ptBestTimesAllMeets"
Const cPVShortName = "ptShort"
Dim pt As PivotTable
Dim sMeets() As String
Dim sEventTimes() As String

Dim iRowOrigin, iColOrigin As Integer 'row and col origins
Dim iRow, iCol, iLastRowInTable As Integer
Dim iRowReturned As Integer
Dim sTemp As String
Dim sName As String 'Name of Swimmer referenced by iThisNameRow.
Dim sThisAgeGroup As String
Dim sThisEvent As String
Dim bStop As Boolean
Dim bFound As Boolean
Dim i As Integer 'loop control
Dim j As Integer 'loop control
Dim iThisNameRow As Integer 'returned by FindNextName
Dim iThisMeetRow As Integer
Const cNameCol = 1  'Columns in PivotTable relative (offset) to first column
Const cMeetCol = 2
Const cTimeCol = 3
Const vbCSV = ","
Const vbCSV1 = ", "
Const cColNewBestTimeMessage = 16
Dim iNameCol, iMeetCol, iTimeCol As Integer
Dim sBestTime As String
Dim sAnswer As VbMsgBoxResult
Dim iNewBestTime As Integer
Dim sNewBestTime As String
Dim collBestMeet As collection
Dim collBestTime As collection 'item contains rank and time
Dim collEventAlias As collection
Dim sSheetName As String
Dim sWorkbookName As String

    sSheetName = ThisWorkbook.Name
    sSheetName = ActiveSheet.Name
    Debug.Print cThisSub & " " & ThisWorkbook.Name
    Debug.Print cThisSub & " " & ActiveSheet.Name
    
    
    'initialize
    iNewBestTime = 0 ' The first message appears in row 2.
    Set collBestMeet = New collection
    Set collBestTime = New collection
    Set collEventAlias = New collection
    'collEventAlias.Add "Medley Relay", "#04-Sr. Boys 200 MR"
    'map freesytle relays to 50 yard freestyle event
    collEventAlias.Add "#r37-Jr. Girls 200 FR-50 Free", "#37-Jr. Girls 200 FR"
    collEventAlias.Add "#r38-Jr. Boys 200 FR-50 Free", "#38-Jr. Boys 200 FR"
    collEventAlias.Add "#r39-Sr. Girls 200 FR-50 Free", "#39-Sr. Girls 200 FR"
    collEventAlias.Add "#r40-Sr. Boys 200 FR-50 Free", "#40-Sr. Boys 200 FR"
    'map Medley Relay events to Back, Breast, Free.
    collEventAlias.Add "#r02-Jr. Boys 200 MR-50 Back", "#r02 MR-50 Back"
    collEventAlias.Add "#r02-Jr. Boys 200 MR-50 Breast", "#r02 MR-50 Breast"
    collEventAlias.Add "#r02-Jr. Boys 200 MR-50 Fly", "#r02 MR-50 Fly"
    collEventAlias.Add "#r04-Sr. Boys 200 MR-50 Fly", "#r04 MR-50 Fly"
    collEventAlias.Add "#r04-Sr. Boys 200 MR-50 Back", "#r04 MR-50 Back"
    collEventAlias.Add "#r04-Sr. Boys 200 MR-50 Breast", "#r04 MR-50 Breast"

    sAnswer = MsgBox("Is this meet '" & cThisMeet & "'", vbYesNo, cThisSub)
    If (sAnswer = vbCancel) Or (sAnswer = vbNo) Then
        MsgBox "Change the declaration of 'cThisMeet'", vbCritical, cThisSub
        End
    End If
    
HereWeGo:
    If cDisableScreenUpdating Then
        Application.ScreenUpdating = False
        Application.EnableEvents = False
    End If
    
    For Each pt In ActiveSheet.PivotTables
        If cPVNAME = pt.Name Then
            Debug.Print "got it"
            iRowOrigin = pt.RowRange.Row
            iColOrigin = pt.RowRange.Column
            iLastRowInTable = pt.RowRange.Rows.count
        End If
    Next
    'put special formatting into the TIME column
    Columns(FindColumnInTopRow("Time")).Select
    Selection.NumberFormat = "00"":""00"".""00"
    Call CreatePivotTable(cPVNAME) 'deletes all existing Pivot Tables and creates this one.
   
    'Find the origin of the pivot table called cPVNAME.
    'ActiveSheet.PivotTables(cPVNAME).PivotSelect "", xlDataAndLabel, True
    'Debug.Print cThisSub & "start column of " & cPVNAME & " is " & ActiveCell.Column 'can use this a colunm to position new one.
    'iRowOrigin = ActiveCell.Row
    'iColOrigin = ActiveCell.Column
    
    bStop = True
    For Each pt In ActiveSheet.PivotTables
        If cPVNAME = pt.Name Then
            iRowOrigin = pt.RowRange.Row
            iColOrigin = pt.RowRange.Column
            iLastRowInTable = iRowOrigin + (pt.RowRange.Rows.count - 1) 'last row number.
            Debug.Print cThisSub & "start column of Pivot Table " & cPVNAME & " is " & iColOrigin & " Last row is " & iLastRowInTable
            bStop = False
        End If
    Next
    If (bStop) Then
        sTemp = MsgBox("Could not locate Pivot Table - stopping program", vbCritical, cThisSub)
        Stop
    End If

    iRow = iRowOrigin
    iCol = iColOrigin
    'Columns in the pivot table
    iNameCol = iCol + cNameCol
    iMeetCol = iCol + cMeetCol
    iTimeCol = iCol + cTimeCol

    'Clear NewBestTimeMessage region
    Range(Cells(iRowOrigin, cColNewBestTimeMessage), Cells(iLastRowInTable, cColNewBestTimeMessage)).Value = ""
    'Clear PivotTable of all Underlined Cells 'MAY NOT NEED THIS as it might have been cleared when Pivot Table Created
    With Range(Cells(iRowOrigin, iColOrigin), Cells(iLastRowInTable, iTimeCol))
        .Borders(xlDiagonalDown).LineStyle = xlNone
        .Borders(xlDiagonalUp).LineStyle = xlNone
        .Borders(xlEdgeLeft).LineStyle = xlNone
        .Borders(xlEdgeTop).LineStyle = xlNone
        .Borders(xlEdgeBottom).LineStyle = xlNone
        .Borders(xlEdgeRight).LineStyle = xlNone
        .Borders(xlInsideVertical).LineStyle = xlNone
        .Borders(xlInsideHorizontal).LineStyle = xlNone
        'i = .Font.Size
    End With
    
    'Clear Delta Time Column
    'The pivot table may have grown or shrunk so clear the delta column.
     With Range(Cells(iRowOrigin, iTimeCol + 1), Cells(iLastRowInTable, iTimeCol + 1))
                        .Font.Bold = False
                        .Font.Underline = False
                        .Font.Italic = False
                        .Value = ""
                        .Font.Size = -1 + Range(Cells(iRowOrigin, iColOrigin), Cells(iLastRowInTable, iTimeCol)).Font.Size 'should use pt.TableRange1.Address or other table properties - see "CopyAndShortenPivotTable"
                        .HorizontalAlignment = xlCenter
                        .VerticalAlignment = xlBottom
                        .WrapText = False
                        .Orientation = 0
                        .AddIndent = False
                        .IndentLevel = 0
                        .ShrinkToFit = False
                        .ReadingOrder = xlContext
                        .MergeCells = False
     End With
    
    'Get the grouping of a Name and associated Meets from the Pivot Table.
    'then do Highlight/Emphasis
    'Jump back to the start of the table.
    iRow = iRowOrigin
    iCol = iColOrigin
  
StepThruLongPivotTable:
       Dim sLastEvent As String
       Dim iEventRank As Integer
       sLastEvent = ""
       iEventRank = 0
    While (iRow <= iLastRowInTable)
       
       iThisNameRow = 0
       ReDim sMeets(0)
       ReDim sEventTimes(0)
       iRowReturned = FindNextName(iRow, iCol, iNameCol, iMeetCol, iTimeCol, iLastRowInTable, sMeets(), sEventTimes(), sThisEvent, sThisAgeGroup, iThisNameRow)
    If iThisNameRow = 0 Then
        Debug.Print cThisSub & "We probably reached the end of the Pivot Table."
        'we probably reached then end of the table but let while loop terminate.
    Else
       'Assuming the Pivot table is well structured.
       'do Highlight processing
       're-initialize array of events and times for next iteration.
        If cDP Then Debug.Print cThisSub & "FindNextName returns " & iRowReturned
        If (sLastEvent = sThisEvent) Then
            'not the first name in this event.
            iEventRank = iEventRank + 1
        Else
            'first name in this event
            sLastEvent = sThisEvent
            If Mid(Cells(iThisNameRow, iNameCol).Text, 1, 1) = "*" Then
                'We have a record holder
                iEventRank = 0
            Else
                iEventRank = 1
            End If
        End If
       'Step through the returned array.
        sName = Cells(iThisNameRow, iNameCol).Value
        If (sName = "Jesse Blitman" And sThisEvent = "#r38-Jr. Boys 200 FR-50 Free") Then MsgBox "found it", , cThisSub
SteppingThroughsMeets:
        Dim bBuiltThisKey As Boolean
        'avoiding Run-time error 457 The key is already assocaited with an element of this collection
        bBuiltThisKey = False 'Avoid duplicate keys. Was building duplicate keys for collections when swimmer got a time in this meet (latest run), that is the fastest AND that time was identical to a previous meet.
        For i = LBound(sMeets) To UBound(sMeets) Step 1
            iThisMeetRow = (iThisNameRow + 1) + i
            'The fastest time is across from the Name.
            'Something to consider.
            'The Pivot table sorts by Age Group, then Event, then Swimmer then Meet(s).
            'It returns the minimum time; that can be from more than one meet.
            'The minimum time is pushed into SBestTime but it may not be a NEW Best Time.
            
            'Highlight/emphasis processing begins here.
            If cDP Then Debug.Print cThisSub & " array index " & i & "  " & sMeets(i) & " = " & sEventTimes(i)
            '#1a
            'Highlite the Meet that the Fastest (min) time came from IF there is more than one meet.
            'It is also possible this time is in more than one meet.
            sBestTime = Cells(iThisNameRow, iTimeCol).Value
            If sEventTimes(i) = sBestTime And (UBound(sEventTimes) > 0) Then
                 Cells(iThisMeetRow, iMeetCol).Font.Bold = True ' HIGHLITE the MEET
            End If
            
BuildTwoCollections:
            '#1b
            Dim sKey As String
            Dim sItem As String
            'Scrape the Best Time information from Long PivotTable and create two collections.
            'collBestTime is used to fill a HeatSheet with Best Times (Rank and Time).
            'collBestMeet is used to append the Meet adjacent to the Short PivotTable.
            sBestTime = Cells(iThisNameRow, iTimeCol).Value
            'Which Meet does this Time belong to?
            If (sEventTimes(i) = sBestTime) And (bBuiltThisKey = False) Then
                'build  keys and items (values).
                bBuiltThisKey = True
                
                'This collection will be used to fill the Heat Sheet.
                'Key = AgeGroup & ":" & Event & ":" & Name
                sKey = Trim(sThisAgeGroup) & cCKS & Trim(sThisEvent) & cCKS & Trim(Cells(iThisNameRow, iNameCol).Text)
                sItem = (CStr(iEventRank) & cRTS & sBestTime)
                collBestTime.Add sItem, sKey
                'retrieve item using this syntax "item=collBestTime(key)"
               
                'This collection will be used with the Short PivotTable.
                'Key = AgeGroup & ":" & Event & ":" & Name & ":" & BestTime
                sKey = sKey & cCKS & sBestTime
                sItem = Cells(iThisMeetRow, iMeetCol).Text
                collBestMeet.Add sItem, sKey
                'retrieve item using this syntax "item=collBestMeet(key)"
                'Note - As implemented this item was retrieved by using an the index (integer) rather than the key.
            End If
            
            '#2 Is this a best time?
OOPS:       If (i = LBound(sMeets)) Then 'best time processing is only for the first event'
                'Is this a NEW Best for this Swimmer/Event/AgeGroup? (that is how Pivot Table is Organized)
                '1)The Event must be from cThisMeet
                '2)The Event has entries from other Meets
                '3)The Pivot table has it as the Fastest (minimum) time
                '4)The time is better than the any previous meets.
                If (InStr(1, sMeets(i), cThisMeet) > 0) And (UBound(sMeets) > 0) And (sEventTimes(i) = sBestTime) Then
                    bFound = vbFalse
                    For j = LBound(sMeets) + 1 To UBound(sMeets) Step 1
                        If (sEventTimes(j)) = sBestTime Then bFound = vbTrue
                    Next
                    If bFound = False Then 'it is a new best time.
                        iNewBestTime = iNewBestTime + 1
                        Cells(iThisNameRow, iTimeCol).Font.Bold = True
                        Cells(iThisNameRow, iNameCol).Font.Bold = True
                        'Cells(iThisNameRow, iNameCol).Value = Cells(iThisNameRow, iNameCol).Value & "***"
                      
GetDeltaTime:
                        'From the past meets, find the smallest time.
                        'Subtract that time from sBestTime. This is the delta.
                        Dim sLastBestTime
                        Dim sDeltaTime
                        sLastBestTime = "999999"
                        For j = i + 1 To UBound(sMeets) Step 1
                            'Whenever you compare EventTimes convert from string to long using cLng.
                            If CLng(sEventTimes(j)) < CLng(sLastBestTime) Then sLastBestTime = sEventTimes(j)
                        Next
                        sDeltaTime = SwimTime(sBestTime, Str(sLastBestTime), 2)
                        Cells(iThisNameRow, iTimeCol + 1).Value = sDeltaTime
                        Cells(iThisNameRow, iTimeCol + 1).NumberFormat = Cells(iThisNameRow, iTimeCol).NumberFormat
                        
                        sNewBestTime = iNewBestTime & vbCSV1 & "New Best Time" & vbCSV1 & sThisAgeGroup & vbCSV1 & sThisEvent & vbCSV1 & sName & vbCSV1 & Format(sBestTime, "00"":""00"".""00") & vbCSV1 & "Down " & Format(sDeltaTime, "00"":""00"".""00")
                        'Tease Format
                        'sNewBestTime = iNewBestTime & vbCSV1 & "New Best Time" & vbCSV1 & sThisAgeGroup & vbCSV1 & sThisEvent & vbCSV1 & sName & vbCSV1 & vbCSV1 & "Down " & Format(sDeltaTime, "00"":""00"".""00")
                        
                        Debug.Print cThisSub & sNewBestTime
                        'builds the side table showing New Best Times
                        Cells(iNewBestTime, cColNewBestTimeMessage).Value = sNewBestTime
                    End If 'it was a best time
                End If 'possibly a best time
            End If '(i = LBound(sMeets))
            
            'Place Underscore to delineate end of this set of Meets for the Swimmer.
            If i = UBound(sMeets) Then 'put underline across Swimmer, Meet and Time column
                    Range(Cells(iThisMeetRow, iNameCol), Cells(iThisMeetRow, iTimeCol)).Select
                    Selection.Borders(xlEdgeBottom).LineStyle = True
            End If

            're-initialize this index in both arrays
            sMeets(i) = ""
            sEventTimes(i) = ""
        Next 'SteppingThrougsMeets label -- loop thru array returned from FindNextName
        iRow = iRowReturned 'where to start looking for next Group in Pivot Table Name.
        If cDP Then Debug.Print cThisSub & "Next iteration begins at row " & iRow
    End If 'processing return from call to FindNextName
    Wend ' Get next Grouping of Name and Meets.
    
    'Completed all highlighting hilite of pivot table.
    'MsgBox "Finished Walking Down Pivot Table", , cThisSub
    
    
    Debug.Print cThisSub & "Finished Walking Down Pivot Table " & cPVNAME
    'where New Best Times set?
    If iNewBestTime = 0 Then
        'Put up a message.
        sNewBestTime = "No new best times set in this meet."
        Cells(iNewBestTime + 1, cColNewBestTimeMessage).Value = sNewBestTime
    Else
        sNewBestTime = iNewBestTime & " new best times this meet."
    End If

    SetBreaksOnPivotTable (cPVNAME)
    
    sTemp = "Inserted page breaks in pivot table " & cPVNAME
    If cDP Then MsgBox sTemp, vbInformation, cThisSub
    Debug.Print cThisSub & sTemp
    
    'create brief copy of pivot table
    Call CopyAndShortenPivotTable(cPVNAME, cPVShortName)

    
    'put the cursor somewhere safe
    Cells(iRowOrigin, iColOrigin).Select
    
    'setup Finished message.
    sTemp = sNewBestTime & " Finis!"
    MsgBox sTemp, , cThisSub
    
    'Append Meet to the Short Pivot Table
    Dim iReturn As Integer
    Call AppendMeetToPV(cPVShortName, collBestMeet, iReturn)
    If (iReturn < 0) Then
        MsgBox "Return code from Sub AppendMeetToPV is " & iReturn, vbCritical, cThisSub
        'continue on
    End If
PutRankAndTimeInHeatSheet:
    Call BoxTimes(collEventAlias, collBestTime, sSheetName)
    
    'release resources
    Set collBestMeet = Nothing
    Set collBestTime = Nothing
    Set collEventAlias = Nothing
    
    'Belt and suspenders
    For Each pt In ActiveSheet.PivotTables
        ActiveSheet.PivotTables(pt.Name).TableRange2.EntireColumn.AutoFit
    Next

    If cDisableScreenUpdating Then
        Application.ScreenUpdating = True
        Application.EnableEvents = True
    End If
    
End Sub

Sub PasteSwimEventsDeprecated()
'read a txt file and APPEND it to the current worksheet.

Const cThisSub = "PasteSwimEvents: "
Dim iRow As Integer
Dim iCol As Integer
Dim MyData As DataObject
    Set MyData = New DataObject
    'MyData.PutInClipboard
    MyData.Clear
    MyData.SetText TextFile_PullData
    'MsgBox MyData.GetText, , cThisSub
    MyData.PutInClipboard
    'see this thread
    'https://social.msdn.microsoft.com/Forums/en-US/48e8c30c-24ee-458e-a873-a4e6e13f5926/dataobject-settext-and-putinclipboard-sequence-puts-invalid-data-hex-63-characters-in-clipboard?forum=isvvba
    'Triggerd by button PasteEvents
    'Is not called by other routines.
    'On Error GoTo ErrorHandler
    'Assume that the swim events are in the paste-buffer.
    
    'Worksheets("Sheet1").Activate
    'find the last row of data in column A (Swim Events)
    Range("A1").Select
    Selection.End(xlDown).Select
    iRow = ActiveCell.Row + 1
    iCol = ActiveCell.Column
    Range(Cells(iRow, iCol), Cells(iRow, iCol)).Select
     
    'paste from the clipboad CSV data and place across columns
    ActiveCell.Activate
    'fuck
    'ActiveSheet.Paste something broke.
    'On Error Resume Next
    'Selection.TextToColumns DataType:=xlDelimited, ConsecutiveDelimiter:=True, Space:=False, Comma:=True
    'If this is the Nth + 1 execution we get this error.
    'If Err.Number = 1004 Then
        'Debug.Print "PasteSwimEvents: Error " & Err.Number '
        'Err.Clear
    'End If
    Columns("A:F").EntireColumn.AutoFit
    MyData.Clear
    'put cursor somewhere convienent
    Cells(1, 1).Select
    Exit Sub
    
'Test Code
'how about opening the file and putting the contents onto the paste buffer.
'something like
'https://msdn.microsoft.com/en-us/vba/excel-vba/articles/worksheet-paste-method-excel
'Worksheets("Sheet1").Range("C1:C5").Copy
'ActiveSheet.Paste Destination:=Worksheets("Sheet1").Range("D1:D5")

'or read entire contents into a variable  and then put that variable into the paste buffer
'https://www.thespreadsheetguru.com/blog/vba-guide-text-files

'https://msdn.microsoft.com/en-us/vba/language-reference-vba/articles/paste-putinclipboard-settext-methods-example
'https://stackoverflow.com/questions/34630704/copy-variables-contents-to-clipboard-vba-excel-2013


'Read a text file and inserts contents into a new worksheet.
'Workbooks.OpenText Filename:="C:\Users\freds_000\SkyDrive\SwimClub\2017\fred.txt ", _
 '   Origin:=xlWindows, StartRow:=1, _
  '      DataType:=xlDelimited, _
'TextQualifier:=xlTextQualifierNone, _
 '   ConsecutiveDelimiter:=False, _
  '  Tab:=False, _
   ' Semicolon:=False, _
    'Comma:=True, _
    'Space:=False, _
    'Other:=False, _
    'Local:=True
    
'Followed by this
    'Dim wbI As Workbook, wbO As Workbook
    'Dim wsI As Worksheet

    'Set wbI = ThisWorkbook
    'Set wsI = wbI.Sheets("Girls") '<~~ Sheet where you want to import

    'Set wbO = Workbooks.Open("C:\Users\freds_000\SkyDrive\SwimClub\2017\fred.txt")
''''''''''''''''''
    
    
'Method TextToColumns
'ActiveCell.TextToColumns _
 '   DataType:=xlDelimited, _
'    TextQualifier:=xlTextQualifierNone, _
'    ConsecutiveDelimiter:=False, _
'    Tab:=False, _
'    Semicolon:=False, _
'    Comma:=True, _
'    Space:=False, _
'    Other:=False
  
'Paste Special
'ActiveSheet.pastspecial Origin:=xlWindows, StartRow:=1, _
'        DataType:=xlDelimited, _
'TextQualifier:=xlTextQualifierNone, _
'    ConsecutiveDelimiter:=False, _
'    Tab:=False, _
'    Semicolon:=False, _
'    Comma:=True, _
'    Space:=False, _
'    Other:=False, _
'    Local:=True
    'TrailingMinusNumbers:=True, _

    'ActiveSheet
    
    

    'wbO.Sheets(1).Cells.Copy wsI.Cells

    'wbO.Close SaveChanges:=False
    
 End Sub
 Function TextFile_PullData() As String
'PURPOSE: Send All Data From Text File To A String Variable
'SOURCE: www.TheSpreadsheetGuru.com
'alternate: https://msdn.microsoft.com/en-us/library/t58aa4dd(v=vs.84).aspx
Const cThisSub = "TextFile_PullData"
Dim TextFile As Integer
Dim FilePath As String
Dim FileContent As String

    FilePath = ThisWorkbook.Path & cEventFilePath
    TextFile = FreeFile
    Open FilePath For Input As TextFile
    FileContent = Input(LOF(TextFile), TextFile)
    'MsgBox FileContent, , cThisSub
    Close TextFile
      
    TextFile_PullData = FileContent
End Function

Function FindNextName(ByVal iRow As Integer, _
ByVal iCol As Integer, _
ByVal iNameCol As Integer, _
ByVal iMeetCol As Integer, _
ByVal iTimeCol As Integer, _
ByVal iLastRowInTable As Integer, _
ByRef sMeet() As String, _
ByRef sEventTime() As String, _
ByRef sThisEvent As String, _
ByRef sThisAgeGroup As String, _
ByRef iNameRow As Integer)

'The calling routine must check iNameRow.
'If data is being passed back iNameRow is <> 0.
'Arguments Returned are
'iLastRowInTable - If  iNameRow <> 0 this points to the next row in the pivot table to begin looking for a the next name
'sMeet array and sEventTime array are the meet name and times
'sThisEvent
'sThisAgeGroup
'iNameRow - the swimmer's name is in this row.

  Const cThisSub = "FindNextName: "
  Const cDP = vbFalse
  
  Dim sName As String
  Dim sTemp As String
  'Dim iNameRow As Integer
  Dim iIndex As Integer
  Dim sThisMeet As String
  
    iNameRow = 0
    While (iRow <= iLastRowInTable)
    'Set the Age Group and Event as they change.
    sTemp = Cells(iRow, iNameCol - 1).Value
    If InStr(1, sTemp, "Age Group", vbTextCompare) > 0 Then
      sThisAgeGroup = sTemp
      If cDP Then Debug.Print cThisSub & ":  New Age Group-> " & sThisAgeGroup
    ElseIf InStr(1, sTemp, "#", vbTextCompare) > 0 Then
      sThisEvent = sTemp
      If cDP Then Debug.Print cThisSub & ": New Event-> " & sThisEvent
    ElseIf Cells(iRow, iNameCol).Value = "" Then
      Debug.Print 'keep searchinig for rows
    Else
          sName = Cells(iRow, iNameCol).Value
          If sName = "" Then
            MsgBox "We have a problem", vbCritical, cThisSub
          End If
          'we have a name
          If cDP Then Debug.Print cThisSub & "Swimmer is " & sName
          iNameRow = iRow 'set-up to look for Meet(s)
          iRow = iRow + 1 'next row
          iIndex = -1 'initialize array index
          While (iRow <= iLastRowInTable)
              sThisMeet = Cells(iRow, iMeetCol).Value
              If sThisMeet <> "" Then
                  iIndex = iIndex + 1
                  If iIndex > 0 Then
                    ReDim Preserve sMeet(iIndex)
                    ReDim Preserve sEventTime(iIndex)
                  End If
                  sMeet(iIndex) = Cells(iRow, iMeetCol).Value
                  sEventTime(iIndex) = Cells(iRow, iTimeCol).Value
                  iRow = iRow + 1
              Else 'no more meets for this swimmer.
                  FindNextName = iRow 'pointing to line after this swimmer's events
                  Exit Function 'Finished gathering Meets one row back.
              End If
          Wend
          'we got her because the preceding While Loop dropped out.
          'we don't have to do anything special because this only happens
          'for the last entry. Let the main While loop drop out event though the irow will be incorrect.
          'FindNextName = iRow
          'Exit Function
    End If
    iRow = iRow + 1
  Wend
  If cDP Then Debug.Print cThisSub & "No More Rows"
  FindNextName = iRow
  'MsgBox "FindNextName is Done", , cThisSub
End Function
Sub CreatePivotTable(ByVal cPVNAME As String)
'Deleles all the PivotTables on this ActiveSheeet not just this one because
'we could have crashed after creating the next one but not assigning a name.
'So this cleans up any previous/incomplete runs.
'Creates Pivot Table cPVNAME
'FJ Modified 2018-12-04

Const cThisSub = "CreatePivotTable: "
Dim sTableDestination As String
Dim sSourceData As String
Dim iMaxRow As Integer
Dim pt As PivotTable
Dim sptnames As String

Debug.Print cThisSub & ": Worksheet is " & ActiveSheet.Name

For Each pt In ActiveSheet.PivotTables
    'sptNames = sptNames & pt.Name & pt.TableRange1.Address & pt.RowRange.Column & pt.RowRange.Row
    'If (pt.Name = cPVNAME) Then
    ActiveSheet.PivotTables(pt.Name).PivotSelect "", xlDataAndLabel, True
    Debug.Print cThisSub & ": Removing pivot table " & pt.Name
    Selection.ClearContents
    'End If
Next



'Create the new pivot table based on event data that starts in column 'MEET'.
'How many rows are in the data source?
'iTemp = FindColumnInTopRow("Meet")
Range(Cells(1, FindColumnInTopRow("Meet")), Cells(1, FindColumnInTopRow("Meet"))).Select
Range(Selection, Selection.End(xlDown)).Select
iMaxRow = Selection.Rows.count
        
        
'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
MayNotWork:
If (vbFalse) Then
    'after trying ways to set the range to a variable it
    'ends up that the recommended way to set the range is through a string
    'as done in this section of code
    'sSourceData = ActiveSheet.Name & "!R1C1:R293C5" 'Template of how it should look.
    'sSourceData = ActiveSheet.Name & "!R1C1:R" & iMaxRow & "C5"
    sSourceData = ActiveSheet.Name & "!R1C" & FindColumnInTopRow("Meet") & ":R" & iMaxRow & "C" & FindColumnInTopRow("Time")
    'sTableDestination = ActiveSheet.Name & "!R1C7"
    sTableDestination = ActiveSheet.Name & "!R1C" & FindColumnInTopRow("Time") + 2
    'Note that two methods are invoked.
    ActiveWorkbook.PivotCaches.Create(SourceType:=xlDatabase, _
        SourceData:=sSourceData, _
        Version:=xlPivotTableVersion14).CreatePivotTable _
        TableDestination:=sTableDestination, _
        TableName:=cPVNAME, _
        DefaultVersion:=xlPivotTableVersion14
Else
    'not recommended BUT I LIKE IT.
    Debug.Print cThisSub & ": CreatePivotTable Using Range references for creating pivot table - It may crash"
    Debug.Print cThisSub & ": Crash may also be do to Version:= selection."
    Dim rSourceData As Range
    Dim rTableDestination As Range
    Set rSourceData = Range(Cells(1, FindColumnInTopRow("Meet")), Cells(iMaxRow, FindColumnInTopRow("Time")))
    'instead of
        'SourceData:=Range(Cells(1, FindColumnInTopRow("Meet")), Cells(iMaxRow, FindColumnInTopRow("Time"))),
    Set rTableDestination = Range(Cells(1, FindColumnInTopRow("Time") + 2), Cells(1, FindColumnInTopRow("Time") + 2))
    'instead of
        'TableDestination:=Range(Cells(1, FindColumnInTopRow("Time") + 2), Cells(1, FindColumnInTopRow("Time") + 2)),
    Debug.Print cThisSub & rSourceData.Address
    Debug.Print cThisSub & rTableDestination.Address
    'Note that two methods are invoked.
    ActiveWorkbook.PivotCaches.Create(SourceType:=xlDatabase, _
        SourceData:=rSourceData, _
        Version:=xlPivotTableVersion14).CreatePivotTable _
        TableDestination:=rTableDestination, _
        TableName:=cPVNAME, _
        DefaultVersion:=xlPivotTableVersion14
End If
'https://msdn.microsoft.com/en-us/vba/excel-vba/articles/pivotcache-createpivottable-method-excel
'https://msdn.microsoft.com/en-us/vba/excel-vba/articles/pivotcaches-create-method-excel
'https://msdn.microsoft.com/en-us/vba/excel-vba/articles/xlpivottableversionlist-enumeration-excel
        
'^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    With ActiveSheet.PivotTables(cPVNAME).PivotFields("Age Group")
        .Orientation = xlRowField
        .Position = 1
    End With
    With ActiveSheet.PivotTables(cPVNAME).PivotFields("Event")
        .Orientation = xlRowField
        .Position = 2
    End With
    With ActiveSheet.PivotTables(cPVNAME).PivotFields("Swimmer")
        .Orientation = xlRowField
        .Position = 3
    End With
    'ActiveSheet.PivotTables(cPVNAME).PivotFields("Swimmer").AutoSort _
     '   xlAscending, "Min of Time"
        
    ActiveSheet.PivotTables(cPVNAME).AddDataField ActiveSheet.PivotTables( _
        cPVNAME).PivotFields("Time"), "Sum of Time", xlSum
    With ActiveSheet.PivotTables(cPVNAME).PivotFields("Sum of Time")
        .Caption = "Min of Time"
        .Function = xlMin
    End With
    
    With ActiveSheet.PivotTables(cPVNAME).PivotFields("Min of Time")
        .NumberFormat = "00"":""00"".""00"
    End With
    
    With ActiveSheet.PivotTables(cPVNAME).PivotFields("Meet")
        .Orientation = xlRowField
        .Position = 4
    End With
    ActiveSheet.PivotTables(cPVNAME).PivotFields("Meet").AutoSort xlDescending _
        , "Meet"
    ActiveSheet.PivotTables(cPVNAME).PivotFields("Swimmer").AutoSort _
        xlAscending, "Min of Time"
        
    ActiveSheet.PivotTables(cPVNAME).PivotFields("Age Group").Subtotals = Array _
        (False, False, False, False, False, False, False, False, False, False, False, False)
    
    With ActiveSheet.PivotTables(cPVNAME).PivotFields("Event")
        .LayoutSubtotalLocation = xlAtBottom
        .LayoutCompactRow = False
    End With
    
    ActiveSheet.PivotTables(cPVNAME).PivotFields("Swimmer").LayoutCompactRow = _
        False
    ActiveSheet.PivotTables(cPVNAME).PivotFields("Event").Subtotals = Array( _
        False, False, False, False, False, False, False, False, False, False, False, False)
    ActiveSheet.PivotTables(cPVNAME).PivotFields("Min of Time").Caption = _
        "Best Time"
        
    'ActiveSheet.PivotTables(cPVNAME).DisplayFieldCaptions = True
    ActiveSheet.PivotTables(cPVNAME).DisplayFieldCaptions = False
    ActiveSheet.PivotTables(cPVNAME).ShowDrillIndicators = False
    'ActiveSheet.PivotTables(cPVNAME).ShowDrillIndicators = True

    'Range("A1").Select don't need this
    'something screwy but this removes the drill indicators
    ActiveSheet.PivotTables(cPVNAME).DisplayFieldCaptions = True
    ActiveSheet.PivotTables(cPVNAME).DisplayFieldCaptions = False
    ActiveSheet.PivotTables(cPVNAME).ShowDrillIndicators = True
    ActiveSheet.PivotTables(cPVNAME).ShowDrillIndicators = False
    
    'get rid of GrandTotal
    'ActiveSheet.PivotTables(cPVNAME).ColumnGrand = False
    'ActiveSheet.PivotTables(cPVNAME).RowGrand = False
        
       With ActiveSheet.PivotTables("ptBestTimesAllMeets")
        .ColumnGrand = False
        .RowGrand = False
       End With


End Sub

Function FindColumnInTopRow(sColName As String) As Integer

'ActiveCell.Rows("1:1").EntireRow.Select
 '   Selection.Find(What:="Time", After:=ActiveCell, LookIn:=xlValues, LookAt _
  '      :=xlWhole, SearchOrder:=xlByColumns, SearchDirection:=xlNext, MatchCase _
  '      :=True, SearchFormat:=False).Activate
  '   Range("Time").Select
     
'FindColumnInTopRow = ActiveCell.Column


Dim rngDateHeader As Range
Dim rngHeaders As Range
Set rngHeaders = Range("1:1") 'Looks in entire first row; adjust as needed.
Set rngDateHeader = rngHeaders.Find(Trim(sColName), , xlValues, xlWhole, xlByColumns, xlNext, True)
FindColumnInTopRow = rngDateHeader.Column
End Function

 Function SetBreaksOnPivotTable(ByVal sName As String)
    ActiveSheet.PivotTables(sName).PivotSelect "", xlDataAndLabel, True
    'ActiveSheet.PivotTables(sName).DisplayFieldCaptions = False

    ActiveSheet.PageSetup.PrintArea = ActiveCell.CurrentRegion.Address 'PageSetup Object
    ActiveSheet.ResetAllPageBreaks
    Selection.Find(What:="9 and 10", After:=ActiveCell, LookIn:=xlValues, _
        LookAt:=xlPart, SearchOrder:=xlByRows, SearchDirection:=xlNext, _
        MatchCase:=False, SearchFormat:=False).Activate
    ActiveWindow.SelectedSheets.HPageBreaks.Add Before:=ActiveCell
    Selection.Find(What:="11 and 12", After:=ActiveCell, LookIn:=xlValues, _
        LookAt:=xlPart, SearchOrder:=xlByRows, SearchDirection:=xlNext, _
        MatchCase:=False, SearchFormat:=False).Activate
    ActiveWindow.SelectedSheets.HPageBreaks.Add Before:=ActiveCell
    Selection.Find(What:="13 +", After:=ActiveCell, LookIn:=xlValues, LookAt _
        :=xlPart, SearchOrder:=xlByRows, SearchDirection:=xlNext, MatchCase:= _
        False, SearchFormat:=False).Activate
    ActiveWindow.SelectedSheets.HPageBreaks.Add Before:=ActiveCell
End Function

Function xPivotTablePageLayout(ByVal sName As String)
'' Not Using because having trouble setting Header and Footer
    ActiveSheet.PivotTables(sName).PivotSelect "", xlDataAndLabel, True
    'ActiveSheet.PivotTables(cPVNAME).ShowDrillIndicators = False

    Application.PrintCommunication = False
    With ActiveSheet.PageSetup
        .PrintTitleRows = ""
        .PrintTitleColumns = ""
    End With
    Application.PrintCommunication = True
    ActiveSheet.PageSetup.PrintArea = ActiveCell.CurrentRegion.Address 'PageSetup Object
    Application.PrintCommunication = False
    With ActiveSheet.PageSetup
        .LeftHeader = ""
        .CenterHeader = ""
        .RightHeader = ""
        .LeftFooter = ""
        .CenterFooter = ""
        .RightFooter = ""
    End With
    Application.PrintCommunication = True
    Application.PrintCommunication = False


    With ActiveSheet.PageSetup
        .LeftHeader = "&""-,Bold""Hewlett Swim Club"
        .CenterHeader = "&P"
        .RightHeader = "&N"
        .LeftFooter = ""
        .LeftFooter = " © 2016 FAJ"
        .CenterFooter = "Rev C"
        .RightFooter = "Only the first leg of a relay counts as a timed event. "
        .LeftMargin = Application.InchesToPoints(0.25)
        .RightMargin = Application.InchesToPoints(0.25)
        .TopMargin = Application.InchesToPoints(0.75)
        .BottomMargin = Application.InchesToPoints(0.75)
        .HeaderMargin = Application.InchesToPoints(0.3)
        .FooterMargin = Application.InchesToPoints(0.3)
        .PrintHeadings = False
        .PrintGridlines = True
        .PrintComments = xlPrintNoComments
        .PrintQuality = 600
        .CenterHorizontally = False
        .CenterVertically = False
        .Orientation = xlPortrait
        .Draft = False
        .PaperSize = xlPaperLetter
        .FirstPageNumber = xlAutomatic
        .Order = xlDownThenOver
        .BlackAndWhite = True
        '.Zoom = False
        .FitToPagesWide = 1
        .FitToPagesTall = False
        .PrintErrors = xlPrintErrorsDisplayed
        .OddAndEvenPagesHeaderFooter = False
        .DifferentFirstPageHeaderFooter = False
        .ScaleWithDocHeaderFooter = True
        .AlignMarginsHeaderFooter = True
        .EvenPage.LeftHeader.Text = ""
        .EvenPage.CenterHeader.Text = ""
        .EvenPage.RightHeader.Text = ""
        .EvenPage.LeftFooter.Text = ""
        .EvenPage.CenterFooter.Text = ""
        .EvenPage.RightFooter.Text = ""
        .FirstPage.LeftHeader.Text = ""
        .FirstPage.CenterHeader.Text = ""
        .FirstPage.RightHeader.Text = ""
        .FirstPage.LeftFooter.Text = ""
        .FirstPage.CenterFooter.Text = ""
        .FirstPage.RightFooter.Text = ""
    End With
    Application.PrintCommunication = True
End Function
Sub CopyAndShortenPivotTable(ByRef sOriginalPivotTableName As String, ByRef sShortPivotTableName As String)
'make a short version of the first pivot table.
'FJ modified 2018-12-04
Const cThisSub = "CopyAndShortenPivotTable: "
Dim pt As PivotTable

'some properties and methods in a Pivot Table.
'sptNames = sptNames & pt.Name & pt.TableRange1.Address & pt.RowRange.Column & pt.RowRange.Row
'sptNames = sptNames & pt.Name & pt.TableRange1.Address & pt.RowRange.Column & pt.RowRange.Row
'ActiveSheet.PivotTables(pt.Name).PivotSelect "", xlDataAndLabel, True
'ActiveSheet.PivotTables


'Delete the short Pivot Table if it exists.
'It may have been deleted intentionally when the other pivot table was deleted.
For Each pt In ActiveSheet.PivotTables
  If pt.Name = sShortPivotTableName Then
    ActiveSheet.PivotTables(pt.Name).PivotSelect "", xlDataAndLabel, True
    'Debug.Print cthissub & ActiveCell.Column 'can use this a colunm to position new one.
    Selection.ClearContents
  End If
Next
    
    'Copy Pivot Table
    ActiveSheet.PivotTables(sOriginalPivotTableName).PivotSelect "", xlDataAndLabel, _
        True
    Selection.Copy
    Dim iRow As Integer
    Dim iCol As Integer
    iRow = ActiveSheet.PivotTables(sOriginalPivotTableName).RowRange.Row
    iCol = ActiveSheet.PivotTables(sOriginalPivotTableName).RowRange.Column + ActiveSheet.PivotTables(sOriginalPivotTableName).TableRange2.Columns.count + 1
    Range(Cells(iRow, iCol), Cells(iRow, iCol)).Select
    ActiveSheet.Paste

'Name it and shorten (remove a PivotField) the new PT
For Each pt In ActiveSheet.PivotTables
  If pt.RowRange.Column = iCol Then
    pt.Name = sShortPivotTableName 'give it a proper name
    ActiveSheet.PivotTables(pt.Name).PivotFields("Meet").Orientation = xlHidden
    'ActiveSheet.PivotTables(pt.Name).PivotFields("Best Time").Visible = vbFalse
    'Select Pivot Table to refresh selected area because it shrunk.
    ActiveSheet.PivotTables(pt.Name).PivotSelect "", xlDataAndLabel, True
  End If
Next
End Sub
Sub xEnumeratePivotTable()
'not using
'can't be done
'tried to prepend 'Place' to swimmer name.
'it effects every occurence of that name in the pivot table.
    'new code
'    Dim iPlace As Integer
'    iRow = iRowOrigin
'    iCol = iColOrigin
'
'    While (iRow < iRowsInTable)
'        Debug.Print Cells(iRow, iCol).Value
'        Debug.Print Cells(iRow, iNameCol).Value
'        If Mid(Cells(iRow, iCol).Value, 1, 1) = "#" Then iPlace = 0
'        If Cells(iRow, iNameCol).Value <> "" Then
'            iPlace = iPlace + 1
'            Cells(iRow, i).Value = iPlace & "  " & Cells(iRow, iNameCol).Value
'            Debug.Print "(" & iPlace & ") " & Cells(iRow, iNameCol).Value
'         End If
'        iRow = iRow + 1
'    Wend ' Get next Grouping of Name and Meets.
End Sub
Function DeltaTime(sTime1, sTime2) As String
'returns difference in time
'the input string notation is "mmssdd" minutes-seconds-hundreths.
'call with sTime1 is <= sTime2.
'returns a string in the same notation as input strings.

Const cThisSub = "DeltaTime: "
Dim lngHSeconds1 As Long 'hundreths of seconds
Dim lngHSeconds2 As Long 'hundreths of seconds
Dim lngDiff As Long
Dim iMins As Integer
Dim iSecs As Integer
    
'Becareful with division calculations as Microsoft will round the result of division.
'You can also use the truncation division operator '\'
    
        'trim and force leading zeros into string
        sTime1 = Format(Trim(sTime1), "000000")
        sTime2 = Format(Trim(sTime2), "000000")
        'quick test - quick conversion to long
    If CLng(sTime1) > CLng(sTime2) Then
        MsgBox cThisSub & "Stopping Program because " & sTime1 & " is less than " & sTime2
        Stop
    Else
        'convert the string notation into a six digit LONG for computation.
        'convert minutes into seconds and shift left 2 places
        'and add seconds and hundreths
        lngHSeconds1 = Int((6000 * Mid(sTime1, 1, 2))) + Int(Mid(sTime1, 3, 4))
        lngHSeconds2 = Int((6000 * Mid(sTime2, 1, 2))) + Int(Mid(sTime2, 3, 4))
        
        'find the difference in seconds to the hundreths.
        lngDiff = lngHSeconds2 - lngHSeconds1 'result will be positive.
        
        'make components so we can convert back to input string notation.
        iMins = Int(lngDiff / 100) 'got seconds
        iMins = Int(iMins / 60) 'convert seconds to minutes
        iSecs = Int(lngDiff / 100) Mod 60 'got seconds
        'format string as minutes & seconds & hundreths
        DeltaTime = Format(iMins, "00") & Format(iSecs, "00") & Format(Right(lngDiff, 2), "00")
    End If
End Function

Function SwimTime(sTime1, sTime2, iOp) As String
'add or subtract SwimTime
'iOp = 1 add
'iOp = 2 subtract sTime1 from sTime2
'the input string notation is "mmssdd" minutes-seconds-hundreths.
'if iOp = 2 call with sTime1 is <= sTime2.
'returns a string in the same notation as input strings.

Const cThisSub = "DeltaTime: "
Dim lngHSeconds1 As Long 'hundreths of seconds
Dim lngHSeconds2 As Long 'hundreths of seconds
Dim LngResult As Long
Dim iMins As Integer
Dim iSecs As Integer
    
'Becareful with division calculations as Microsoft will round the result of division.
'You can also use the truncation division operator '\'
    
        'trim and force leading zeros into string
        sTime1 = Format(Trim(sTime1), "000000")
        sTime2 = Format(Trim(sTime2), "000000")
        'quick test - quick conversion to long
        'convert the string notation into a six digit LONG for computation.
        'convert minutes into seconds and shift left 2 places
        'and add seconds and hundreths
        lngHSeconds1 = Int((6000 * Mid(sTime1, 1, 2))) + Int(Mid(sTime1, 3, 4))
        lngHSeconds2 = Int((6000 * Mid(sTime2, 1, 2))) + Int(Mid(sTime2, 3, 4))
        
        If iOp = 1 Then
            LngResult = lngHSeconds2 + lngHSeconds1 'result will be positive.
        ElseIf iOp = 2 Then
        'find the difference in seconds to the hundreths.
            LngResult = lngHSeconds2 - lngHSeconds1 'result will be positive.
        End If
       
        'make components so we can convert back to input string notation.
        iMins = Int(LngResult / 100) 'got seconds
        iMins = Int(iMins / 60) 'convert seconds to minutes
        iSecs = Int(LngResult / 100) Mod 60 'got seconds
        'format string as minutes & seconds & hundreths
        SwimTime = Format(iMins, "00") & Format(iSecs, "00") & Format(Right(LngResult, 2), "00")
End Function
Function AddTimes() As String
'adds a range of swimtimes
'foundation routine for adding a range of swimtimes
Dim iRow As Integer
Dim iCol As Integer
Dim myRange As Range
Dim cell As Variant
Dim sTotal As String

    'ActiveCell.Select
    iRow = ActiveCell.Row
    iCol = ActiveCell.Column
    Set myRange = Range(Cells(iRow, iCol), Cells(iRow + 3, iCol))
    sTotal = "000000"
    For Each cell In myRange
        sTotal = SwimTime(sTotal, cell, 1)
    Next
    AddTimes = sTotal

End Function

Sub PasteSwimEvents()
Dim iRow, iCol As Integer
Dim wbEvent As Workbook
Dim wbThis As Workbook
Dim sEventFilePath As String
    'Locate the last event record on this worksheet
    sEventFilePath = ThisWorkbook.Path & cEventFilePath
    Range("A1").Select
    Selection.End(xlDown).Select
    iRow = ActiveCell.Row + 1
    iCol = ActiveCell.Column
    Range(Cells(iRow, iCol), Cells(iRow, iCol)).Select
    'Save reference to this workbook
    Set wbThis = ThisWorkbook
    'Get the data from the Events file
    Set wbEvent = Workbooks.Open(sEventFilePath)
    'get all the data
    Range("a1").Select
    Range(Selection, Selection.End(xlToRight)).Select
    Range(Selection, Selection.End(xlDown)).Select
    'put data on clipboard
    Selection.Copy
     
    'paste from the clipboad CSV data and place across columns
    wbThis.Activate
    ActiveSheet.Paste
    'wbO.Sheets(1).Cells.Copy wsI.Cells 'explore using this.
    'https://stackoverflow.com/questions/5163265/disable-clipboard-prompt-in-excel-vba-on-workbook-close
    ActiveCell.Select
    ActiveCell.Copy
    wbEvent.Close SaveChanges:=False

End Sub

Private Sub AppendMeetToPV(ByVal sThisPvName, ByRef colBestMeet, ByRef iReturn As Integer)
    'For each Name in the short PivotTable get the Meet from the collection.
    'FJ 2018-12-04
    Const cThisSub = "AppendMeetToPV:"
    Dim iCollectionCount As Integer
    Dim sMyString As String
    Dim iThisRow As Integer
    Dim iKey As Integer
    Dim iNameCol As Integer
    Dim iMeetCol As Integer
    Dim pv As PivotTable
    Dim iRowStart As Integer
    Dim iLastRowInTable As Integer
    
    iReturn = -1 'bad return code
    Set pv = ActiveSheet.PivotTables(sThisPvName)
    iRowStart = pv.RowRange.Row
    iMeetCol = pv.RowRange.Column + pv.TableRange2.Columns.count 'appears in column after PV
    iLastRowInTable = iRowStart + (pv.RowRange.Rows.count - 1) 'last row number.
    iNameCol = pv.RowRange.Column + 1 'Name in second column of PV
    iKey = 1
    iCollectionCount = colBestMeet.count
    
    'Clear/format the column where the Meet will show adjacent to the short pivot table.
    With Range(Cells(iRowStart, iMeetCol), Cells(iLastRowInTable, iMeetCol))
                        .Font.Bold = False
                        .Font.Underline = False
                        .Font.Italic = False
                        .Value = ""
                        .Font.Size = Range(Cells(iRowStart, pv.RowRange.Column), Cells(iLastRowInTable, pv.RowRange.Column)).Font.Size
                        .HorizontalAlignment = xlLeft
                        .VerticalAlignment = xlBottom
                        .WrapText = False
                        .Orientation = 0
                        .AddIndent = False
                        .IndentLevel = 0
                        .ShrinkToFit = False
                        .ReadingOrder = xlContext
                        .MergeCells = False
     End With
    
    
    
    'Append the Meet to the row if the row contains a name.
    'The intention was to build a key to the collection and access the item.
    'This is a fast dumb way to do it.
    For iThisRow = iRowStart To iLastRowInTable
        sMyString = Cells(iThisRow, iNameCol).Value 'get name
        If (sMyString = "") Then 'there is no name in this row.
            Cells(iThisRow, iMeetCol).Value = "" 'clear previous contents of cell.
        Else
           sMyString = colBestMeet(iKey) 'get meet from the Collection
           sMyString = Mid(sMyString, InStr(1, sMyString, " ") + 1)
           Cells(iThisRow, iMeetCol) = sMyString 'append Meet to column adjacent to the pivot table.
           iKey = iKey + 1
           'Cells(iThisRow, iMeetCol).Font.Underline = True
        End If
    Next
    'quality control test
    If (iKey = iCollectionCount + 1) Then
        MsgBox "All Meets Appended to Swimmmers in Pivot Table " & sThisPvName, , cThisSub
        iReturn = 0
    End If
    Set pv = Nothing
End Sub

Sub BoxTimes(ByRef collEventAias As collection, ByRef collBestTime As collection, ByVal sWorksheetName As String)
'Copyright 2017 FAJ
'Author FAJ 12/06/2018
'Derived from a similar subroutine in module EventMaker.
'Navigates the heatsheet.
'Fill the heatsheet with rank/times.

Const cThisSub = "BoxTimes:"
Dim iRecordCount As Integer ' the number of events generated.
Dim iRow As Integer
Dim iCol As Integer
Dim iRowAll As Integer
Dim iRowsInTable As Integer 'end of section for event table
Dim iColEvent As Integer
Dim sMeetName As String 'Example 11/22/2016 Intramural
Dim sEvent As String
Dim sTemp As String
Dim bStop As Boolean

Const cLastLine = "Net"
Const cRowOrig = 1 'This is where the table begins.
Const cColOrig = 1

    iRowsInTable = 0
   
    Debug.Print cThisSub & Now
    'This worksheet is either Boys or Girls.
    'Which heatsheet are we going to use; BoysTimes or GirlsTimes?
    sTemp = sWorksheetName & "Times"
    Sheets(sTemp).Activate
        
    sMeetName = Trim(Cells(cRowOrig, cColOrig).Value)
    
    'Figure out the last row of the input table.
    iRowsInTable = FindLastRowInTable(cRowOrig, cColOrig, cLastLine)
    
    'find next (or first) age-group and get rank/time.
    iRow = cRowOrig
    iCol = cColOrig
    iRecordCount = 0 'ultimately contains total record count of all groups.
    While (iRow < iRowsInTable)
        'Debug.Print "Get Age Group"
        iRow = NextAgeGroupV1(iRow, iCol, sMeetName, iRecordCount, collEventAias, collBestTime)
            iRow = iRow + 1 'next age-group starts here or this was the last age-group
        'Debug.Print iRow
    Wend
    'Debug.Print Now
    Debug.Print "MakeEvents: Record Count " & iRecordCount
    MsgBox ("MakeEvents: Created " & iRecordCount & " events. Finis")
    
    End Sub
Function NextAgeGroupV1(ByRef iRowOrig As Integer, ByRef iColOrig As Integer, ByRef sMeetName As String, ByRef iRecordCount As Integer, ByRef collEventAlias As collection, ByRef collBestTime As collection) As Integer
    'Derived from a similar function in module EventMaker.
    'Walking down the heatsheet
    'Locate first group
    'For each Event in Group (event are in columns), use the names to find rank/time for that event
    'Return with pointer to next group.
    
    'For an age-group, constructs a collection key (retrieves rank and time) and writes rank and time into the BoysTimes or GirlsTimes sheet.
    
    'This function is called repeatedly; the first time it processes the first Age-Group. Subsequent calls process the next Age-Group.
    'The function returns a row as integer. It is a pointer to the last row in the processed age group.
    'The calling function stops calling this functions when the row returned is equal to the maximum rows in the table.
    'iRowOrig and iColOrig as input give "hints" as to the head of this Age-Group.'The exact row is found programmatically to accomodate earlier implementations of the MeetSheet.
    'sMeetName as input, for building events-strings.(Not in this version)
    'iRecordCount as input and output; the net of all the event-strings created
    'iEventFileHandle - reference to file that Events are written to.
    
    Const cThisSub = "NextAgeGroup: "
    Dim sTemp As String
    Dim iTemp As Integer
    Dim iRowThisAgeGroup 'Row that contains this Age-Group string.
    Dim iRowOfEvents As Integer 'Row containing event-names.
    Dim iRowNamesStart As Integer 'First row with swimmer-name.
    Dim iRowAgeEnd As Integer 'end of section for age-group.
    Dim iRow As Integer
    Dim iCol As Integer
    Dim iColEvent As Integer ' Row Header - The specific event; eg '#18-50 Back'
    Dim iColEventFirst As Integer
    Dim iColEventLast As Integer
    
    'Columns from worksheet
    Dim sGroupName As String
    Dim sEventNo As String
    Dim sEventNoCopy As String 'sEventNo may be changed this one is original
    Dim sHeat As String
    Dim sName As String
    Dim sTime As String
    
    Dim sThisEvent As String
    Dim sThisGroupName As String
    Dim sThisSwitchedEventNo As String
    Dim rTempRng As Range
    Dim bStop As Boolean

    'sGroupNames = Array("A  Age Group (8 and Under)", "B  Age Group (9 and 10)", "C  Age Group (11 and 12)", "D  Age Group (13 +)")
    'The Group Names should be added to the spreedsheet
    
    'iRowOrigin is the row where this Age-Group begins
    'iRowOfEvents = iRowOrig + 1
    'iRowNamesStart = iRowOfEvents + 1
    
    'What row contains the events and what row contains the names?
    iRow = iRowOrig
    iCol = iColOrig
    bStop = False
    While (bStop = False)
        sTemp = Cells(iRow, iCol).Value
        If Mid(sTemp, 1) = "First Name" Then
            iRowOfEvents = iRow
            iRowNamesStart = iRow + 1
            iRowThisAgeGroup = iRow - 1
            'Get this Group Name
            sThisGroupName = Trim(Cells(iRowThisAgeGroup, iCol)) '********
            bStop = True
        Else
            iRow = iRow + 1
        End If
    Wend
        
    'Find the last row for this age-group.
    iRowAgeEnd = FindLastRowForThisAgeGroup(iRowOrig, iColOrig)

    'Find the first and last event-columns
    'https://msdn.microsoft.com/en-us/vba/excel-vba/articles/range-find-method-excel
    bStop = False
    iRow = iRowOfEvents
    iColEventFirst = 0
    With Range(iRow & ":" & iRow)
    Set rTempRng = .Find("#", , xlValues, xlPart, xlByColumns, xlNext)
    If Not rTempRng Is Nothing Then
        iColEventFirst = rTempRng.Column
        Do
            iColEventLast = rTempRng.Column
            Set rTempRng = .FindNext(rTempRng)
        Loop While Not rTempRng Is Nothing And rTempRng.Column <> iColEventFirst
    End If
    End With
    If iColEventFirst = 0 Then
        MsgBox cThisSub & "Can not find any events descriptors like #21-25 Breast"
        Stop
    End If
    
    For iColEvent = iColEventFirst To iColEventLast Step 1   'scan across columns in groups of 3
     If (Mid(Cells(iRowOfEvents, iColEvent).Value, 1, 1)) <> "#" Then
     Else
        'do something for each name (swimmer).
        iRow = 0
        iCol = iColOrig
        For iRow = iRowNamesStart To iRowAgeEnd - 1 Step 1 'the swimmers in this age-group - scan down list
            'Get and Reset these variables.
            sGroupName = sThisGroupName 'The group name could be modified in this loop
            sEventNo = Trim(Cells(iRowOfEvents, iColEvent).Value) 'event
            sHeat = Trim(UCase(Cells(iRow, iColEvent - 1).Value))
            sName = Trim(Cells(iRow, iCol).Value) & " " & Trim(Cells(iRow, iCol + 1).Value) 'swimmers's name
            sTime = Trim(Cells(iRow, iColEvent).Value) 'time
            
            'Begin Processing Events
ConstructKeyForRetrievingItemFromCollection:
            'get rank/time for this event.
            Dim sRtn As String
            'Is there redirection for this event?
            sRtn = KeyExists(collEventAlias, sEventNo) ' Is this event redirected?
            If sRtn = "" Then
                Call PostRankAndTime(iRow, iColEvent, sGroupName, sEventNo, sName, collBestTime)
            ElseIf sRtn = "Medley Relay" Then
                'PLACE CODE HERE
                Debug.Print "Medley Relay ***>  " & sEventNo
                If Mid(sEventNo, 1, 3) = "#01" Then
                    '
                ElseIf Mid(sEventNo, 1, 3) = "#02" Then
                    '
                ElseIf Mid(sEventNo, 1, 3) = "#03" Then
                    '
                ElseIf Mid(sEventNo, 1, 3) = "#04" Then
                    sEventNo = "#r04-Sr. Boys 200 MR-50 Back"
                    Call PostRankAndTime(iRow, iColEvent, sGroupName, sEventNo, sName, collBestTime)
                    sEventNo = "#r04-Sr. Boys 200 MR-50 Breast"
                    Call PostRankAndTime(iRow, iColEvent, sGroupName, sEventNo, sName, collBestTime)
                    sEventNo = "#r04-Sr. Boys 200 MR-50 Fly"
                    Call PostRankAndTime(iRow, iColEvent, sGroupName, sEventNo, sName, collBestTime)
                End If
            ElseIf sRtn <> "" Then
                sEventNo = sRtn
                Call PostRankAndTime(iRow, iColEvent, sGroupName, sEventNo, sName, collBestTime)
            End If
            
        Next 'next person - walking down rows
     End If 'finished processing all names for this Event
    Next 'next event - walking across columns
    NextAgeGroupV1 = iRowAgeEnd 'pointer to starting row of next group.
End Function
Private Sub PostRankAndTime(ByVal iRow As Integer, ByVal iColEvent As Integer, ByVal sGroupName As String, ByVal sEventNo As String, ByVal sName As String, ByRef collBestTime As collection)
    'Construct a key and retrieve the rank/time from the collBestTime collection.
    'If an item is not returned, try locating the DQ of the same event.
    
    Dim sKey As String
    Dim sTime As String
    Dim i As Integer
    Dim sTemp As String
    Dim vRankRtn As Variant
    Dim sTimeRtn As String
    
    Const cThisSub = "PostRankTime:"
    
            'Do I need a DQ version of this Event?
            'Construct key and get Time for Event. If an item isn't returned construct a key as DQ of this Event.
            sKey = sGroupName & ":" & sEventNo & ":" & sName
            Debug.Print cThisSub & " Collection Key: " & sKey
            'get item
            sTime = KeyExists(collBestTime, sKey)
            If sTime = "" Then 'is there a dq time?
                i = InStr(1, sKey, ":")
                i = InStr(i + 1, sKey, ":")
                sTemp = Mid(sKey, 1, i - 1) & "**DQ**" & Mid(sKey, i)
                sKey = sTemp
                sTime = KeyExists(collBestTime, sKey)
                If sTime <> "" Then 'found the DQ version of event.
                    Debug.Print cThisSub & "Got a DQ Collection Key: " & sKey & " w/Time " & sTime
                    Call GetRankAndTime(sTime, cRTS, vRankRtn, sTimeRtn)
                    sTime = "DQ" & cRTS & sTimeRtn 'We don't rank the DQs.
                    'procede as a normal event
                End If
            End If
PutInBox:
            If sTime = "" Then 'clean-up from previous run - put blanks in rank and time cells.
               Call WriteRankAndTime("", "", iRow, iColEvent)
            Else 'We have Rank/Time
                Call GetRankAndTime(sTime, cRTS, vRankRtn, sTimeRtn)
                Call WriteRankAndTime(vRankRtn, sTimeRtn, iRow, iColEvent)
            End If

End Sub
Function KeyExists(ByRef coll As collection, ByVal sKey As String) As String
    'Function returns value in collection if the key exists otherwise returns "".
    'if the key doesn't exist an 'Error' is thrown.
    '2018-12-07 FAJ

    On Error GoTo ErrorHandler
    KeyExists = coll(sKey)
    Exit Function
ErrorHandler:
    KeyExists = ""
End Function
Sub GetRankAndTime(ByVal sTime As String, ByRef sRankTimeSeparator As String, ByRef vRankRtn As Variant, ByRef sTimeRtn As String)
'Decode sTime and return Rank and Time.
'2018-12-07 FAJ

Dim i As Integer
Dim vTemp As Variant
Const cThisSub = "GetRankAndTime:"
    'sTime is encoded as nnnn+=time
    'where nnnn is typical one or two digits.
    'rank
    i = InStr(1, sTime, sRankTimeSeparator)
    vRankRtn = Mid(sTime, 1, i - 1)
    'time
    sTimeRtn = Mid(sTime, i + 2)
    
End Sub
Sub WriteRankAndTime(ByVal vRank As Variant, ByVal vTime As Variant, ByVal iRow As Integer, ByVal iColEvent As Integer)
'Output Rand and Time to their respective cells along with cell format properties.
'2018-12-07 FAJ
               'rank goes in heat/lane column
               With Cells(iRow, iColEvent - 1)
                .HorizontalAlignment = xlRight
                '.NumberFormat = "@"
                .NumberFormat = "0"
                .Value = vRank
               End With
               If vRank <= 2 Then
                Cells(iRow, iColEvent - 1).Font.Bold = True
               End If
               'Time goes in event column
               With Cells(iRow, iColEvent)
                .HorizontalAlignment = xlCenter
                .NumberFormat = "00"":""00"".""00"
                .Value = vTime
               End With
End Sub

